name: reusable-1

on:
  workflow_call:
    inputs:
      environment_target:
        description: 'Specifies the target environment for the workflow execution (e.g., dev, uat, prod).'
        type: string
        required: true
    outputs:
      super_secret:
        description: "Super secret value"
        value: ${{ jobs.reusable.outputs.super_secret }}

jobs:
  reusable:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_target }}
    outputs:
      super_secret: ${{ steps.reusable.outputs.super_secret }}
    steps:
      - name: â¬‡ï¸ Checkout Code
        uses: actions/checkout@v4

      - name: ðŸ› ï¸ Reusable 1
        id: reusable
        shell: bash
        run: |
          echo "Running reusable 1"
          echo "super_secret=$SUPER_SECRET" >> GITHUB_OUTPUT
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
