name: reusable-1

on:
  workflow_call:
    inputs:
      environment_target:
        description: 'Specifies the target environment for the workflow execution (e.g., dev, uat, prod).'
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_target }}
    steps:
      - name: â¬‡ï¸ Checkout Code
        uses: actions/checkout@v4

      - name: ðŸ› ï¸ Reusable 1
        shell: bash
        run: |
          echo "Running reusable 1"
          echo "$SUPER_SECRET" >> hello_world.txt
          cat hello_world.txt
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}