name: reusable-1

on:
  workflow_call:
    inputs:
      environment_target:
        description: 'Specifies the target environment for the workflow execution (e.g., dev, uat, prod).'
        type: string
        required: true
    outputs:
      super_secret:
        description: "Super secret value"
        value: ${{ jobs.reusable.outputs.super_secret }}

jobs:
  reusable:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_target }}

    outputs:
      super_secret: ${{ steps.reusable_step.outputs.super_secret }}

    steps:
      - name: â¬‡ï¸ Checkout Code
        uses: actions/checkout@v4

      - name: ðŸ› ï¸ Reusable 1
        id: reusable_step
        shell: bash
        run: |
          echo "Running reusable 1"

          # Guardamos el secret en un archivo
          echo "$SUPER_SECRET" > file.txt

          # Exportamos el output (nota el $)
          echo "super_secret=$(cat file.txt)" >> $GITHUB_OUTPUT
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
